# Generated by Django 3.1.6 on 2021-02-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='section',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateTimeField(null=True),
        ),
    ]
