# Generated by Django 3.1.6 on 2021-02-12 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210212_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteLesson',
            fields=[
                ('lesson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.lesson')),
                ('link', models.CharField(max_length=512)),
                ('note', models.FileField(upload_to='course_files/')),
            ],
            bases=('core.lesson',),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='course_images/'),
        ),
    ]
