# Generated by Django 3.1.6 on 2021-05-25 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lesson_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkLesson',
            fields=[
                ('lesson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.lesson')),
                ('title', models.CharField(max_length=512)),
                ('link', models.CharField(max_length=512)),
            ],
            bases=('core.lesson',),
        ),
    ]
