# Generated by Django 3.1.6 on 2021-02-12 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210212_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notelesson',
            name='link',
        ),
    ]
