# Generated by Django 3.1.6 on 2021-02-14 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210212_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='session',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.session'),
            preserve_default=False,
        ),
    ]
