# Generated by Django 3.1.6 on 2021-02-18 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_question_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseTeacher',
        ),
    ]
