# Generated by Django 3.1.6 on 2021-02-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_courseteacher'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sectionteacher',
            unique_together={('section', 'teacher')},
        ),
    ]
