# Generated by Django 3.1.6 on 2021-02-18 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210218_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionteacher',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.section'),
        ),
        migrations.AlterField(
            model_name='sectionteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher'),
        ),
    ]
