# Generated by Django 3.1.6 on 2021-02-19 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210218_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='assessment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.assessment'),
            preserve_default=False,
        ),
    ]
