# Generated by Django 3.1.6 on 2021-02-19 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_answer_assessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='after_session',
        ),
        migrations.AddField(
            model_name='assessment',
            name='end_date',
            field=models.DateTimeField(default='2021-02-19T13:26:14+0000'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment',
            name='start_date',
            field=models.DateTimeField(default='2021-02-19T13:26:14+0000'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('total_mark', models.FloatField()),
                ('assessment', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='core.assessment')),
                ('student', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
        ),
    ]
