# Generated by Django 3.1.6 on 2021-02-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210219_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
