# Generated by Django 3.1.6 on 2021-02-19 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_assessment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='assessment_type',
        ),
    ]
