# Generated by Django 3.1.6 on 2021-02-20 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0014_remove_assessment_assessment_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadquestion',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='multiplechoicequestion',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='shortquestion',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='question',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_core.question_set+', to='contenttypes.contenttype'),
        ),
    ]
