# Generated by Django 3.1.6 on 2021-02-20 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210220_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadquestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='multiplechoicequestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shortquestion',
            options={},
        ),
        migrations.RemoveField(
            model_name='question',
            name='polymorphic_ctype',
        ),
    ]
