# Generated by Django 3.1.6 on 2021-02-20 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210220_1442'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessmentquestion',
            unique_together={('assessment', 'question')},
        ),
    ]
